// Warm-up, overview jump, add set, session edit. node tools/smoke3.mjs [base] [out]
import { chromium } from 'playwright';
const base = process.argv[2] || 'http://localhost:8080/';
const out = process.argv[3] || '.';
const errors = [];
const b = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const p = await (await b.newContext({ viewport: { width: 412, height: 860 }, isMobile: true, hasTouch: true })).newPage();
p.on('pageerror', (e) => errors.push('pageerror: ' + e.message));
p.on('console', (m) => { if (m.type() === 'error') errors.push('console: ' + m.text()); });
const click = async (sel) => { await p.locator(sel).first().click(); await p.waitForTimeout(250); };
const shot = async (n) => { await p.waitForTimeout(500); await p.screenshot({ path: `${out}/${n}.png` }); };
await p.goto(base); await p.waitForTimeout(500);
for (let i = 0; i < 2; i++) await click('[data-next]');
await click('[data-goal="fit"]'); await click('[data-level="beginner"]'); await click('[data-next]'); await click('[data-next]'); await click('[data-next]'); await click('[data-finish]');
await p.evaluate(() => (location.hash = '#/workout/bw-strength'));
await p.waitForTimeout(400);
await p.locator('#warm').check({ force: true });
await click('#start');
await click('#pSkip');
await shot('w1-warmup');
const pill = await p.locator('#pPhase').textContent();
console.log('phase:', pill);
await click('#ovw');
await shot('w2-overview');
await click('[data-entry="6"]'); // squat (warmup 5 + push-up 0 -> entry 5, squat 6)
await shot('w3-jumped');
console.log('now:', await p.locator('.p-name').textContent());
await click('#addSet');
console.log('dots:', await p.locator('.set-dots i').count());
await click('#pMain');
await click('#quit'); await click('[data-a="save"]');
await p.waitForTimeout(1200);
await click('#done');
await p.evaluate(() => (location.hash = '#/progress?tab=history'));
await p.waitForTimeout(400);
await click('#pbody a.li');
await click('[data-edit]');
await shot('w4-edit');
await click('[data-name="reps"] [data-d="1"]');
await click('[data-a="save"]');
await shot('w5-edited');
console.log(errors.length ? errors.join('\n') : 'NO ERRORS');
await b.close();
