// End-to-end smoke test: node tools/smoke.mjs [baseUrl] [outDir]
import { chromium } from 'playwright';
const base = process.argv[2] || 'http://localhost:8080/';
const out = process.argv[3] || '.';
const errors = [];
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: +(process.env.W || 412), height: +(process.env.H || 860) }, deviceScaleFactor: 1, isMobile: true, hasTouch: true, colorScheme: process.env.DARK ? 'dark' : 'light' });
const p = await ctx.newPage();
p.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') errors.push(`console.${m.type()}: ${m.text()}`); });
p.on('pageerror', (e) => errors.push('pageerror: ' + e.message));
const shot = async (n) => { await p.waitForTimeout(600); await p.screenshot({ path: `${out}/${n}.png` }); };
const click = async (sel) => { await p.locator(sel).first().click(); await p.waitForTimeout(250); };

await p.goto(base);
await p.waitForTimeout(800);
await shot('01-welcome');
await click('[data-next]');
await p.fill('#name', 'Nitesh');
await click('[data-next]');
await click('[data-goal="strength"]');
await click('[data-level="intermediate"]');
await click('[data-equipment="dumbbell"]');
await shot('02-equipment');
await click('[data-next]');
await click('[data-next]');
await p.fill('#bw', '72');
await click('[data-next]');
await shot('03-plan');
await click('[data-finish]');
await p.waitForTimeout(500);
await shot('04-home');
await p.evaluate(() => (location.hash = '#/workouts'));
await shot('05-workouts');
await p.evaluate(() => (location.hash = '#/workout/starter-7'));
await shot('06-workout-detail');
await p.evaluate(() => (location.hash = '#/exercises'));
await shot('07-library');
await p.evaluate(() => (location.hash = '#/exercise/push-up'));
await shot('08-exercise');
// timed circuit: speed through
await p.evaluate(() => (location.hash = '#/play/desk-break'));
await p.waitForTimeout(800);
await shot('09-player-ready');
for (let i = 0; i < 3; i++) await click('#pSkip');
await shot('10-player-work');
await click('#pSkip');
await shot('11-player-rest');
// skip to the end
for (let i = 0; i < 40; i++) { if (!(await p.locator('#pSkip').count())) break; await p.locator('#pSkip').click(); await p.waitForTimeout(60); }
await p.waitForTimeout(1200);
await shot('12-summary');
await click('#rate [data-r="4"]');
await click('#done');
// sets workout
await p.evaluate(() => (location.hash = '#/play/db-upper'));
await p.waitForTimeout(600);
await click('#pSkip');
await shot('13-player-set');
await click('#pMain');
await shot('14-set-rest');
await click('#skipRest');
await click('#pMain');
await click('#quit');
await shot('15-quit-sheet');
await click('[data-a="save"]');
await p.waitForTimeout(1200);
await shot('16-summary-sets');
await click('#done');
await p.evaluate(() => (location.hash = '#/progress'));
await shot('17-progress');
await p.evaluate(() => (location.hash = '#/progress?tab=history'));
await shot('18-history');
await p.evaluate(() => (location.hash = '#/progress?tab=body'));
await shot('19-body');
await p.evaluate(() => (location.hash = '#/me'));
await shot('20-profile');
await p.evaluate(() => (location.hash = '#/build'));
await shot('21-builder');
await p.evaluate(() => (location.hash = '#/'));
await shot('22-home-after');
console.log(errors.length ? errors.join('\n') : 'NO ERRORS');
await b.close();
